services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - ftp-server

  ftp-server:
    build: ./backend
    ports:
      - "21:21"
      - "5000:5000"
    volumes:
      - db-data:/backend/db

volumes:
  db-data: